filebeat.modules:
- module: mysql
  error:
    enabled: true
    var.paths: ["/var/log/mysql/mysql_error.log*"]
  
  slowlog:
    enabled: true
    var.paths: ["/var/log/mysql/mariadb-slow.log*"]


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
# ======================= Elasticsearch template setting =======================
setup.template.settings:
  index.number_of_shards: 1
# =================================== Kibana ===================================
setup.kibana:
  host: "192.168.1.213:5601"

# ---------------------------- Elasticsearch Output ----------------------------

output.elasticsearch:
  hosts: ["192.168.1.213:9200"]
  username: "elastic"
  password: "changeme"
  allow_older_versions: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~



