#! /bin/sh
### BEGIN INIT INFO
# Provides:          initFilebeat
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: 
# Description: 
### END INIT INFO

filebeat setup
service filebeat start
